export const DEVICE_LOG_FLAG_BACKLOG = 0x01;
export const DEVICE_LOG_FLAG_DROPPED = 0x02;
export const BLE_ERROR_STORAGE_KEY_UNAVAILABLE = 0x14;

export const DEVICE_DIAGNOSTICS_EVT_META = 0x90;
export const DEVICE_DIAGNOSTICS_EVT_SIGNATURE = 0x91;
export const DEVICE_DIAGNOSTICS_EVT_END = 0x92;
export const DEVICE_DIAGNOSTICS_EVT_DETAIL = 0x95;
