name: bota_flutter_sdk
description: Flutter facade for connecting applications to Bota Pin and Bota Note devices.
version: 1.2.0-beta.9
homepage: https://docs.bota.dev
repository: https://github.com/bota-dev/app-sdk/tree/main/frameworks/flutter/bota_flutter_sdk
environment:
  sdk: ">=3.11.0 <4.0.0"
  flutter: ">=3.41.0"
dependencies:
  flutter:
    sdk: flutter
  meta: ^1.19.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 6.0.0
  pigeon: 28.0.0
flutter:
  plugin:
    platforms:
      android:
        package: dev.bota.sdk.flutter
        pluginClass: BotaFlutterSdkPlugin
      ios:
        pluginClass: BotaFlutterSdkPlugin
