[package]
name = "xtask"
version = "1.1.0"
edition = "2024"
license = "MIT"
publish = false

[dependencies]
bota-device-sdk-core = { path = "../../core/device-sdk-core" }
chacha20poly1305 = "0.11.0"
hmac = "0.13.0"
hpke = { version = "0.14.0", default-features = false, features = ["alloc", "chacha", "x25519"] }
p256 = { version = "0.14.0", default-features = false, features = ["ecdsa", "sha256"] }
rand_chacha = "0.10.0"
semver = "1.0.27"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.150"
serde_yaml_ng = "0.10.0"
sha2 = "0.11.0"
toml = "1.1.4"

[lib]
path = "src/lib.rs"

[[bin]]
name = "xtask"
path = "src/main.rs"
