[package]
name = "bota-device-sdk-ffi"
version = "1.0.1"
edition = "2024"
rust-version = "1.98"
license = "Apache-2.0"
description = "Native ABI for the Bota App SDK core"
repository = "https://github.com/bota-dev/app-sdk"
publish = false

[lib]
crate-type = ["rlib", "staticlib", "cdylib"]

[dependencies]
bota-device-sdk-core = { path = "../../core/device-sdk-core", version = "=1.0.1" }
