// Generated by cargo xtask client-identity generate. Do not edit.
package dev.bota.sdk

internal object SdkIdentity {
    const val PACKAGE = "dev.bota:bota-app-sdk"
    const val VERSION = "2.0.0-beta.2"
}
