#ifndef BOTA_DEVICE_SDK_H
#define BOTA_DEVICE_SDK_H

/*
 * Bota Device SDK native ABI v1.
 *
 * Ownership and lifetime rules:
 * - An engine pointer must be NULL or a live value returned by engine_new.
 * - A live engine must not be freed while another call is using it.
 * - engine_free must be called at most once for each non-NULL engine.
 * - An error pointer is SDK-owned and must be passed exactly once to error_free.
 * - Slices returned by error_view are borrowed from the error owner and become
 *   invalid when that owner is freed.
 * - Output arguments must point to writable storage and must not retain an
 *   earlier SDK-owned value.
 *
 * Violating pointer, lifetime, or single-free rules is undefined behavior.
 * Status errors report recoverable operation failures, not invalid foreign
 * memory.
 */

#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

static const uint32_t BOTA_DEVICE_SDK_ABI_VERSION = 1;

typedef struct BotaDeviceSdkEngineV1 BotaDeviceSdkEngineV1;
typedef struct BotaDeviceSdkErrorV1 BotaDeviceSdkErrorV1;
typedef struct BotaDeviceSdkPacketV1 BotaDeviceSdkPacketV1;

typedef struct BotaDeviceSdkSliceV1 {
    const uint8_t *data;
    uint64_t len;
} BotaDeviceSdkSliceV1;

static const uint32_t BOTA_DEVICE_SDK_V1_COMMAND_RANGE_START = 0x0100;
static const uint32_t BOTA_DEVICE_SDK_V1_COMMAND_DISCOVER_DEVICES = 0x0101;
static const uint32_t BOTA_DEVICE_SDK_V1_COMMAND_CONNECT = 0x0102;
static const uint32_t BOTA_DEVICE_SDK_V1_COMMAND_RECONNECT = 0x0103;
static const uint32_t BOTA_DEVICE_SDK_V1_COMMAND_PROVISION = 0x0104;
static const uint32_t BOTA_DEVICE_SDK_V1_COMMAND_TRANSFER_RECORDING = 0x0105;
static const uint32_t BOTA_DEVICE_SDK_V1_COMMAND_UPLOAD_RECORDING = 0x0106;
static const uint32_t BOTA_DEVICE_SDK_V1_COMMAND_UPDATE_FIRMWARE = 0x0107;
static const uint32_t BOTA_DEVICE_SDK_V1_COMMAND_READ_DEVICE_LOGS = 0x0108;
static const uint32_t BOTA_DEVICE_SDK_V1_COMMAND_FACTORY_RESET = 0x0109;
static const uint32_t BOTA_DEVICE_SDK_V1_COMMAND_RESUME_FACTORY_RESET = 0x010A;
static const uint32_t BOTA_DEVICE_SDK_V1_COMMAND_TRANSFER_ENCRYPTED_RECORDING = 0x010C;
static const uint32_t BOTA_DEVICE_SDK_V1_HOST_EVENT_RANGE_START = 0x0200;
static const uint32_t BOTA_DEVICE_SDK_V1_HOST_EVENT_BLE_SCAN_RESULT = 0x0201;
static const uint32_t BOTA_DEVICE_SDK_V1_HOST_EVENT_BLE_SCAN_STOPPED = 0x0202;
static const uint32_t BOTA_DEVICE_SDK_V1_HOST_EVENT_BLE_CONNECTED = 0x0203;
static const uint32_t BOTA_DEVICE_SDK_V1_HOST_EVENT_BLE_SERVICES_DISCOVERED = 0x0204;
static const uint32_t BOTA_DEVICE_SDK_V1_HOST_EVENT_BLE_SUBSCRIBED = 0x0205;
static const uint32_t BOTA_DEVICE_SDK_V1_HOST_EVENT_BLE_DISCONNECTED = 0x0206;
static const uint32_t BOTA_DEVICE_SDK_V1_HOST_EVENT_BLE_READ_COMPLETED = 0x0207;
static const uint32_t BOTA_DEVICE_SDK_V1_HOST_EVENT_BLE_WRITE_COMPLETED = 0x0208;
static const uint32_t BOTA_DEVICE_SDK_V1_HOST_EVENT_BLE_NOTIFICATION = 0x0209;
static const uint32_t BOTA_DEVICE_SDK_V1_HOST_EVENT_BLE_FAILED = 0x020A;
static const uint32_t BOTA_DEVICE_SDK_V1_HOST_EVENT_TIMER_FIRED = 0x0210;
static const uint32_t BOTA_DEVICE_SDK_V1_HOST_EVENT_CHECKPOINT_LOADED = 0x0211;
static const uint32_t BOTA_DEVICE_SDK_V1_HOST_EVENT_CHECKPOINT_SAVED = 0x0212;
static const uint32_t BOTA_DEVICE_SDK_V1_HOST_EVENT_CONNECTION_IDENTITY_SAVED = 0x0213;
static const uint32_t BOTA_DEVICE_SDK_V1_HOST_EVENT_FACTORY_RESET_RESULT_SAVED = 0x0214;
static const uint32_t BOTA_DEVICE_SDK_V1_HOST_EVENT_FACTORY_RESET_RESULT_DELETED = 0x0215;
static const uint32_t BOTA_DEVICE_SDK_V1_HOST_EVENT_PERSISTENCE_FAILED = 0x0216;
static const uint32_t BOTA_DEVICE_SDK_V1_HOST_EVENT_PROVISIONING_MATERIAL_PREPARED = 0x0217;
static const uint32_t BOTA_DEVICE_SDK_V1_HOST_EVENT_FACTORY_RESET_GRANT_PREPARED = 0x0218;
static const uint32_t BOTA_DEVICE_SDK_V1_HOST_EVENT_HOST_MATERIAL_FAILED = 0x0219;
static const uint32_t BOTA_DEVICE_SDK_V1_HOST_EVENT_RECORDING_SINK_TRUNCATED = 0x021A;
static const uint32_t BOTA_DEVICE_SDK_V1_HOST_EVENT_RECORDING_SINK_APPEND_COMPLETED = 0x021B;
static const uint32_t BOTA_DEVICE_SDK_V1_HOST_EVENT_RECORDING_SINK_FINALIZED = 0x021C;
static const uint32_t BOTA_DEVICE_SDK_V1_HOST_EVENT_RECORDING_SINK_INTEGRITY_FAILED = 0x021D;
static const uint32_t BOTA_DEVICE_SDK_V1_HOST_EVENT_RECORDING_SINK_FAILED = 0x021E;
static const uint32_t BOTA_DEVICE_SDK_V1_HOST_EVENT_FIRMWARE_CHUNK_READ = 0x021F;
static const uint32_t BOTA_DEVICE_SDK_V1_HOST_EVENT_FIRMWARE_BLOB_FAILED = 0x0220;
static const uint32_t BOTA_DEVICE_SDK_V1_HOST_EVENT_SECRET_LOADED = 0x0221;
static const uint32_t BOTA_DEVICE_SDK_V1_HOST_EVENT_SECRET_STORED = 0x0222;
static const uint32_t BOTA_DEVICE_SDK_V1_HOST_EVENT_NETWORK_DOWNLOAD_PROGRESS = 0x0223;
static const uint32_t BOTA_DEVICE_SDK_V1_HOST_EVENT_NETWORK_DOWNLOAD_COMPLETED = 0x0224;
static const uint32_t BOTA_DEVICE_SDK_V1_HOST_EVENT_NETWORK_UPLOAD_PROGRESS = 0x0225;
static const uint32_t BOTA_DEVICE_SDK_V1_HOST_EVENT_NETWORK_UPLOAD_COMPLETED = 0x0226;
static const uint32_t BOTA_DEVICE_SDK_V1_HOST_EVENT_NETWORK_FAILED = 0x0227;
static const uint32_t BOTA_DEVICE_SDK_V1_HOST_EVENT_ENCRYPTED_UPLOAD_V2_CHECKPOINT_LOADED = 0x022B;
static const uint32_t BOTA_DEVICE_SDK_V1_HOST_EVENT_ENCRYPTED_UPLOAD_V2_SINK_TRUNCATED = 0x022C;
static const uint32_t BOTA_DEVICE_SDK_V1_HOST_EVENT_ENCRYPTED_UPLOAD_V2_SESSION_PREPARED = 0x022D;
static const uint32_t BOTA_DEVICE_SDK_V1_HOST_EVENT_ENCRYPTED_UPLOAD_V2_TRANSFER_STARTED = 0x022E;
static const uint32_t BOTA_DEVICE_SDK_V1_HOST_EVENT_ENCRYPTED_UPLOAD_V2_RESUME_REJECTED = 0x022F;
static const uint32_t BOTA_DEVICE_SDK_V1_HOST_EVENT_ENCRYPTED_UPLOAD_V2_WINDOW_STAGED = 0x0230;
static const uint32_t BOTA_DEVICE_SDK_V1_HOST_EVENT_ENCRYPTED_UPLOAD_V2_CHECKPOINT_SAVED = 0x0231;
static const uint32_t BOTA_DEVICE_SDK_V1_HOST_EVENT_ENCRYPTED_UPLOAD_V2_WINDOW_ACKNOWLEDGED = 0x0232;
static const uint32_t BOTA_DEVICE_SDK_V1_HOST_EVENT_ENCRYPTED_UPLOAD_V2_TRANSFER_COMPLETED = 0x0233;
static const uint32_t BOTA_DEVICE_SDK_V1_HOST_EVENT_ENCRYPTED_UPLOAD_V2_ARTIFACTS_STAGED = 0x0234;
static const uint32_t BOTA_DEVICE_SDK_V1_HOST_EVENT_ENCRYPTED_UPLOAD_V2_RECEIPT_ACCEPTED = 0x0235;
static const uint32_t BOTA_DEVICE_SDK_V1_HOST_EVENT_ENCRYPTED_UPLOAD_V2_RECORDING_CONFIRMED = 0x0236;
static const uint32_t BOTA_DEVICE_SDK_V1_HOST_EVENT_ENCRYPTED_UPLOAD_V2_MIXED_PROFILE = 0x0237;
static const uint32_t BOTA_DEVICE_SDK_V1_HOST_EVENT_ENCRYPTED_UPLOAD_V2_FAILED = 0x0238;
static const uint32_t BOTA_DEVICE_SDK_V1_HOST_EFFECT_RANGE_START = 0x0300;
static const uint32_t BOTA_DEVICE_SDK_V1_HOST_EFFECT_TIMER_SCHEDULE = 0x0301;
static const uint32_t BOTA_DEVICE_SDK_V1_HOST_EFFECT_TIMER_CANCEL = 0x0302;
static const uint32_t BOTA_DEVICE_SDK_V1_HOST_EFFECT_PERSISTENCE_LOAD_CHECKPOINT = 0x0303;
static const uint32_t BOTA_DEVICE_SDK_V1_HOST_EFFECT_PERSISTENCE_SAVE_CHECKPOINT = 0x0304;
static const uint32_t BOTA_DEVICE_SDK_V1_HOST_EFFECT_PERSISTENCE_DELETE_CHECKPOINT = 0x0305;
static const uint32_t BOTA_DEVICE_SDK_V1_HOST_EFFECT_PERSISTENCE_SAVE_CONNECTION_IDENTITY = 0x0306;
static const uint32_t BOTA_DEVICE_SDK_V1_HOST_EFFECT_PERSISTENCE_SAVE_FACTORY_RESET_RESULT = 0x0307;
static const uint32_t BOTA_DEVICE_SDK_V1_HOST_EFFECT_PERSISTENCE_DELETE_FACTORY_RESET_RESULT = 0x0308;
static const uint32_t BOTA_DEVICE_SDK_V1_HOST_EFFECT_SECURE_STORAGE_READ = 0x0309;
static const uint32_t BOTA_DEVICE_SDK_V1_HOST_EFFECT_SECURE_STORAGE_WRITE = 0x030A;
static const uint32_t BOTA_DEVICE_SDK_V1_HOST_EFFECT_SECURE_STORAGE_DELETE = 0x030B;
static const uint32_t BOTA_DEVICE_SDK_V1_HOST_EFFECT_BLE_START_SCAN = 0x0310;
static const uint32_t BOTA_DEVICE_SDK_V1_HOST_EFFECT_BLE_STOP_SCAN = 0x0311;
static const uint32_t BOTA_DEVICE_SDK_V1_HOST_EFFECT_BLE_CONNECT = 0x0312;
static const uint32_t BOTA_DEVICE_SDK_V1_HOST_EFFECT_BLE_DISCOVER_SERVICES = 0x0313;
static const uint32_t BOTA_DEVICE_SDK_V1_HOST_EFFECT_BLE_DISCONNECT = 0x0314;
static const uint32_t BOTA_DEVICE_SDK_V1_HOST_EFFECT_BLE_READ = 0x0315;
static const uint32_t BOTA_DEVICE_SDK_V1_HOST_EFFECT_BLE_WRITE = 0x0316;
static const uint32_t BOTA_DEVICE_SDK_V1_HOST_EFFECT_BLE_SUBSCRIBE = 0x0317;
static const uint32_t BOTA_DEVICE_SDK_V1_HOST_EFFECT_BLE_UNSUBSCRIBE = 0x0318;
static const uint32_t BOTA_DEVICE_SDK_V1_HOST_EFFECT_NETWORK_DOWNLOAD = 0x0320;
static const uint32_t BOTA_DEVICE_SDK_V1_HOST_EFFECT_NETWORK_UPLOAD = 0x0321;
static const uint32_t BOTA_DEVICE_SDK_V1_HOST_EFFECT_PROGRESS = 0x0328;
static const uint32_t BOTA_DEVICE_SDK_V1_HOST_EFFECT_PREPARE_PROVISIONING = 0x0330;
static const uint32_t BOTA_DEVICE_SDK_V1_HOST_EFFECT_PREPARE_FACTORY_RESET_GRANT = 0x0331;
static const uint32_t BOTA_DEVICE_SDK_V1_HOST_EFFECT_RECORDING_SINK_TRUNCATE = 0x0338;
static const uint32_t BOTA_DEVICE_SDK_V1_HOST_EFFECT_RECORDING_SINK_APPEND = 0x0339;
static const uint32_t BOTA_DEVICE_SDK_V1_HOST_EFFECT_RECORDING_SINK_FINALIZE = 0x033A;
static const uint32_t BOTA_DEVICE_SDK_V1_HOST_EFFECT_RECORDING_SINK_DISCARD = 0x033B;
static const uint32_t BOTA_DEVICE_SDK_V1_HOST_EFFECT_FIRMWARE_BLOB_READ = 0x0340;
static const uint32_t BOTA_DEVICE_SDK_V1_HOST_EFFECT_ENCRYPTED_UPLOAD_V2_LOAD_CHECKPOINT = 0x0342;
static const uint32_t BOTA_DEVICE_SDK_V1_HOST_EFFECT_ENCRYPTED_UPLOAD_V2_DELETE_CHECKPOINT = 0x0343;
static const uint32_t BOTA_DEVICE_SDK_V1_HOST_EFFECT_ENCRYPTED_UPLOAD_V2_TRUNCATE_SINK = 0x0344;
static const uint32_t BOTA_DEVICE_SDK_V1_HOST_EFFECT_ENCRYPTED_UPLOAD_V2_PREPARE_SESSION = 0x0345;
static const uint32_t BOTA_DEVICE_SDK_V1_HOST_EFFECT_ENCRYPTED_UPLOAD_V2_START_TRANSFER = 0x0346;
static const uint32_t BOTA_DEVICE_SDK_V1_HOST_EFFECT_ENCRYPTED_UPLOAD_V2_REPAIR_WINDOW = 0x0347;
static const uint32_t BOTA_DEVICE_SDK_V1_HOST_EFFECT_ENCRYPTED_UPLOAD_V2_SAVE_CHECKPOINT = 0x0348;
static const uint32_t BOTA_DEVICE_SDK_V1_HOST_EFFECT_ENCRYPTED_UPLOAD_V2_ACKNOWLEDGE_WINDOW = 0x0349;
static const uint32_t BOTA_DEVICE_SDK_V1_HOST_EFFECT_ENCRYPTED_UPLOAD_V2_STAGE_ARTIFACTS = 0x034A;
static const uint32_t BOTA_DEVICE_SDK_V1_HOST_EFFECT_ENCRYPTED_UPLOAD_V2_AWAIT_RECEIPT = 0x034B;
static const uint32_t BOTA_DEVICE_SDK_V1_HOST_EFFECT_ENCRYPTED_UPLOAD_V2_CONFIRM_WITH_RECEIPT = 0x034C;
static const uint32_t BOTA_DEVICE_SDK_V1_HOST_EFFECT_ENCRYPTED_UPLOAD_V2_ABORT = 0x034D;
static const uint32_t BOTA_DEVICE_SDK_V1_NOTIFICATION_RANGE_START = 0x0400;
static const uint32_t BOTA_DEVICE_SDK_V1_NOTIFICATION_STARTED = 0x0401;
static const uint32_t BOTA_DEVICE_SDK_V1_NOTIFICATION_DEVICE_DISCOVERED = 0x0402;
static const uint32_t BOTA_DEVICE_SDK_V1_NOTIFICATION_CONNECTION_ESTABLISHED = 0x0403;
static const uint32_t BOTA_DEVICE_SDK_V1_NOTIFICATION_PROGRESS = 0x0404;
static const uint32_t BOTA_DEVICE_SDK_V1_NOTIFICATION_RETRYING = 0x0405;
static const uint32_t BOTA_DEVICE_SDK_V1_NOTIFICATION_DEVICE_UPLOAD_PRESERVED = 0x0406;
static const uint32_t BOTA_DEVICE_SDK_V1_NOTIFICATION_BLE_FALLBACK_READY = 0x0407;
static const uint32_t BOTA_DEVICE_SDK_V1_NOTIFICATION_FIRMWARE_PROGRESS = 0x0408;
static const uint32_t BOTA_DEVICE_SDK_V1_NOTIFICATION_DEVICE_LOG = 0x0409;
static const uint32_t BOTA_DEVICE_SDK_V1_NOTIFICATION_COMPLETED = 0x040A;
static const uint32_t BOTA_DEVICE_SDK_V1_NOTIFICATION_CANCELLED = 0x040B;
static const uint32_t BOTA_DEVICE_SDK_V1_NOTIFICATION_FAILED = 0x040C;
static const uint32_t BOTA_DEVICE_SDK_V1_NOTIFICATION_ENCRYPTED_UPLOAD_V2_STAGED = 0x0410;
static const uint32_t BOTA_DEVICE_SDK_V1_PROTOCOL_VALUE_RANGE_START = 0x0500;
static const uint32_t BOTA_DEVICE_SDK_V1_PROTOCOL_DECODE_DEVICE_STATUS = 0x0501;
static const uint32_t BOTA_DEVICE_SDK_V1_PROTOCOL_DECODE_RECORDING_LIST = 0x0502;
static const uint32_t BOTA_DEVICE_SDK_V1_PROTOCOL_DECODE_TRANSFER_PACKET = 0x0503;
static const uint32_t BOTA_DEVICE_SDK_V1_PROTOCOL_DECODE_TRIGGER_UPLOAD_RESPONSE = 0x0504;
static const uint32_t BOTA_DEVICE_SDK_V1_PROTOCOL_DECODE_ACK = 0x0505;
static const uint32_t BOTA_DEVICE_SDK_V1_PROTOCOL_DECODE_FIRMWARE_STATUS = 0x0506;
static const uint32_t BOTA_DEVICE_SDK_V1_PROTOCOL_DECODE_WIFI_CONFIG_RESULT = 0x0507;
static const uint32_t BOTA_DEVICE_SDK_V1_PROTOCOL_DECODE_FACTORY_RESET_RESULT = 0x0508;
static const uint32_t BOTA_DEVICE_SDK_V1_PROTOCOL_DECODE_CONNECTION_SETTINGS = 0x0509;
static const uint32_t BOTA_DEVICE_SDK_V1_PROTOCOL_DECODE_DEVICE_LOGS = 0x050A;
static const uint32_t BOTA_DEVICE_SDK_V1_PROTOCOL_ENCODE_ACK = 0x0510;
static const uint32_t BOTA_DEVICE_SDK_V1_PROTOCOL_ENCODE_TRANSFER_COMMAND = 0x0511;
static const uint32_t BOTA_DEVICE_SDK_V1_PROTOCOL_ENCODE_DEVICE_COMMAND = 0x0512;
static const uint32_t BOTA_DEVICE_SDK_V1_PROTOCOL_ENCODE_FIRMWARE_UPLOAD_START = 0x0513;
static const uint32_t BOTA_DEVICE_SDK_V1_PROTOCOL_ENCODE_FIRMWARE_DATA = 0x0514;
static const uint32_t BOTA_DEVICE_SDK_V1_PROTOCOL_ENCODE_FIRMWARE_WINDOW_ACK = 0x0515;
static const uint32_t BOTA_DEVICE_SDK_V1_PROTOCOL_ENCODE_FIRMWARE_UPLOAD_VERIFY = 0x0516;
static const uint32_t BOTA_DEVICE_SDK_V1_PROTOCOL_ENCODE_FIRMWARE_STATUS = 0x0517;
static const uint32_t BOTA_DEVICE_SDK_V1_PROTOCOL_ENCODE_CONNECTION_SETTINGS = 0x0518;
static const uint32_t BOTA_DEVICE_SDK_V1_PROTOCOL_ENCODE_BOUNDED_PAYLOAD = 0x0519;
static const uint32_t BOTA_DEVICE_SDK_V1_PROTOCOL_ENCODE_WIFI_GRANT = 0x051A;
static const uint32_t BOTA_DEVICE_SDK_V1_PROTOCOL_ENCODE_WIFI_SCAN = 0x051B;
static const uint32_t BOTA_DEVICE_SDK_V1_PROTOCOL_ENCODE_PROVISIONING_CHUNKS = 0x051C;
static const uint32_t BOTA_DEVICE_SDK_V1_PROTOCOL_DECODE_ENCRYPTED_UPLOAD_V2_CAPABILITY = 0x0520;
static const uint32_t BOTA_DEVICE_SDK_V1_PROTOCOL_DECODE_ENCRYPTED_UPLOAD_V2_SIGNED_BLOB = 0x0521;
static const uint32_t BOTA_DEVICE_SDK_V1_PROTOCOL_DECODE_ENCRYPTED_UPLOAD_V2_TRANSFER_OR_STATUS = 0x0522;

static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_TYPE_UNSIGNED = 1;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_TYPE_SIGNED = 2;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_TYPE_BOOL = 3;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_TYPE_UTF8 = 4;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_TYPE_BYTES = 5;

static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_TIMEOUT_MS = 1;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_ALLOW_DUPLICATES = 2;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_SERIAL_NUMBER = 3;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_PERIPHERAL_ID = 4;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_NAME = 5;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_ADVERTISED_ADDRESS = 6;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_RSSI = 7;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_STORED_PERIPHERAL_ID = 8;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_STORED_NAME = 9;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_SCAN_TIMEOUT_MS = 10;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_CONNECTION_TIMEOUT_MS = 11;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_MATERIAL_ID = 12;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_RECORDING_UUID = 13;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_SINK_ID = 14;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_TOTAL_UNITS = 15;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_UPLOAD_ID = 16;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_DESTINATION_ID = 17;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_FIRMWARE_VERSION = 18;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_FIRMWARE_SIZE_BYTES = 19;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_FIRMWARE_CRC32 = 20;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_DOWNLOAD_ID = 21;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_COMMAND_ID = 22;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_GRANT_ID = 23;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_RESULT_CODE = 24;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_DELETED_RECORDING_COUNT = 25;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_TIMER_ID = 26;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_DELAY_MS = 27;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_CHECKPOINT = 28;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_KEY = 29;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_VALUE = 30;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_SERVICE_UUID = 31;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_CHARACTERISTIC_UUID = 32;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_PAYLOAD = 33;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_WITH_RESPONSE = 34;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_UPLOAD_SOURCE = 35;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_COMPLETED_UNITS = 36;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_EXPECTED_CRC32 = 37;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_SEQUENCE = 38;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_OFFSET = 39;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_MAX_LENGTH = 40;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_NONCE = 41;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_DEVICE_PUBLIC_KEY = 42;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_ATTEMPT = 43;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_CONNECTION_MODE = 44;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_FIRMWARE_PHASE = 45;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_LOG_MESSAGE = 46;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_ERROR_CODE = 47;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_RETRYABLE = 48;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_PROTOCOL_STATUS = 49;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_ERROR_DETAIL = 50;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_IS_BACKLOG = 51;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_PLATFORM_CODE = 52;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_REASON_CODE = 53;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_DURABLE_UNITS = 54;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_API_ENDPOINT = 55;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_DEVICE_TOKEN = 56;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_MTU = 57;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_GRANT = 58;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_TRANSFER_ID = 59;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_STATUS_CODE = 60;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_PROTOCOL_VARIANT = 61;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_BATTERY_PERCENT = 62;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_BATTERY_MV = 63;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_STORAGE_TOTAL_MB = 64;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_STORAGE_USED_MB = 65;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_DEVICE_STATE = 66;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_PENDING_RECORDINGS = 67;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_TIMESTAMP = 68;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_FLAGS = 69;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_LTE_STATUS_RAW = 70;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_LTE_SIGNAL_QUALITY = 71;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_WIFI_STATUS_RAW = 72;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_MODEM_IMEI = 73;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_MODEM_ICCID = 74;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_MODEM_OPERATOR = 75;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_MODEM_RAT = 76;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_MODEM_BAND = 77;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_MODEM_APN = 78;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_MODEM_SIM_STATUS = 79;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_MODEM_CSQ = 80;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_MODEM_IP_ADDRESS = 81;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_MODEM_VOLTAGE_MV = 82;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_MODEM_FIRMWARE = 83;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_MODEM_ROAMING = 84;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_RECORDING_COUNT = 85;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_STARTED_AT = 86;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_DURATION_MS = 87;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_FILE_SIZE_BYTES = 88;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_AUDIO_CODEC = 89;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_ENCRYPTED = 90;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_CHECKSUM = 91;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_BYTES_SENT = 92;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_EPHEMERAL_PUBLIC_KEY = 93;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_SALT = 94;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_ACCEPTED = 95;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_ACK_TYPE = 96;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_COMMAND = 97;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_RESULT = 98;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_WIFI_RESULT = 99;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_SUPPORTED_VERSION = 100;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_ENABLED_WIFI = 101;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_ENABLED_CELLULAR = 102;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_CONNECTION_TYPE = 103;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_CELLULAR_IDLE_TIMEOUT = 104;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_WIFI_IDLE_TIMEOUT = 105;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_STREAMING_ENABLED = 106;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_STREAMING_FLUSH_INTERVAL = 107;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_HEARTBEAT_WIFI = 108;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_HEARTBEAT_CELLULAR = 109;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_HEARTBEAT_UNKNOWN_MASK = 110;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_DEVICE_MODEL = 111;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_CAPACITY = 112;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_CHUNK = 113;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_MESSAGE_TYPE = 127;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_TRANSPORT_SESSION_ID = 128;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_RECORDING_GENERATION = 129;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_CIPHERTEXT_LENGTH = 130;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_PLAINTEXT_LENGTH = 131;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_UPLOAD_SESSION_UUID = 132;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_CHECKPOINT_REVISION = 133;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_WINDOW_PACKETS = 134;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_DATA_PAYLOAD_BYTES = 135;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_MISSING_SEQUENCE = 136;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_CAPABILITY_FLAGS = 137;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_MAX_SIGNED_BLOB_BYTES = 138;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_MAX_MANIFEST_BYTES = 139;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_CHECKPOINT_INTERVAL = 140;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_MAX_MISSING_SEQUENCES = 141;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_MANIFEST_SHA256 = 142;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_PREFIX_SHA256 = 143;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_CIPHERTEXT_SHA256 = 144;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_BLOCK_COUNT = 145;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_COMPLETION_STATE = 146;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_STORAGE_FORMAT = 147;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_LIST_REVISION = 148;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_DURATION_SECONDS = 149;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_BODY_LENGTH = 150;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_BLOB_KIND = 151;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_WRITE_ID = 152;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_PHASE = 153;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_TRANSPORT_PROFILE = 154;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_DETAIL_CODE = 155;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_PROFILE_VERSION = 156;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_REQUEST_FLAGS = 157;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_FIRST_SEQUENCE = 158;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_LAST_SEQUENCE = 159;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_WINDOW_INDEX = 160;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_AUTHORIZATION_SHA256 = 161;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_RECEIPT_SHA256 = 162;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_PROGRESS_PERCENT = 163;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_DURABLE_CIPHERTEXT_BYTES = 164;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_OWNER_REVISION = 165;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_UPLOAD_PROFILE = 166;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_UPLOAD_SECURITY_POLICY = 167;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_MANIFEST_LENGTH = 168;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_MAX_DATA_PAYLOAD_BYTES = 169;
static const uint32_t BOTA_DEVICE_SDK_V1_FIELD_MAX_WINDOW_PACKETS = 170;

static const uint64_t BOTA_DEVICE_SDK_V1_CAPABILITY_BLE = (UINT64_C(1) << 0);
static const uint64_t BOTA_DEVICE_SDK_V1_CAPABILITY_TIMER = (UINT64_C(1) << 1);
static const uint64_t BOTA_DEVICE_SDK_V1_CAPABILITY_PERSISTENCE = (UINT64_C(1) << 2);
static const uint64_t BOTA_DEVICE_SDK_V1_CAPABILITY_SECURE_STORAGE = (UINT64_C(1) << 3);
static const uint64_t BOTA_DEVICE_SDK_V1_CAPABILITY_NETWORK_TRANSFER = (UINT64_C(1) << 4);
static const uint64_t BOTA_DEVICE_SDK_V1_CAPABILITY_PROGRESS = (UINT64_C(1) << 5);
static const uint64_t BOTA_DEVICE_SDK_V1_CAPABILITY_HOST_MATERIAL = (UINT64_C(1) << 6);
static const uint64_t BOTA_DEVICE_SDK_V1_CAPABILITY_RECORDING_SINK = (UINT64_C(1) << 7);
static const uint64_t BOTA_DEVICE_SDK_V1_CAPABILITY_FIRMWARE_BLOB = (UINT64_C(1) << 8);

typedef struct BotaDeviceSdkFieldViewV1 {
    uint32_t field_id;
    uint32_t field_type;
    uint64_t unsigned_value;
    int64_t signed_value;
    BotaDeviceSdkSliceV1 data;
} BotaDeviceSdkFieldViewV1;

typedef struct BotaDeviceSdkPacketViewV1 {
    uint32_t abi_version;
    uint32_t kind;
    uint32_t operation;
    uint32_t reserved;
    uint64_t request_id;
    uint64_t cancellation_id_high;
    uint64_t cancellation_id_low;
    const BotaDeviceSdkFieldViewV1 *fields;
    uint64_t field_count;
} BotaDeviceSdkPacketViewV1;

static const uint32_t BOTA_DEVICE_SDK_V1_OPERATION_VALIDATE = 1;
static const uint32_t BOTA_DEVICE_SDK_V1_OPERATION_DECODE = 2;
static const uint32_t BOTA_DEVICE_SDK_V1_OPERATION_ENCODE = 3;
static const uint32_t BOTA_DEVICE_SDK_V1_OPERATION_DISCOVER = 4;
static const uint32_t BOTA_DEVICE_SDK_V1_OPERATION_CONNECT = 5;
static const uint32_t BOTA_DEVICE_SDK_V1_OPERATION_RECONNECT = 6;
static const uint32_t BOTA_DEVICE_SDK_V1_OPERATION_PROVISION = 7;
static const uint32_t BOTA_DEVICE_SDK_V1_OPERATION_TRANSFER_RECORDING = 8;
static const uint32_t BOTA_DEVICE_SDK_V1_OPERATION_UPLOAD = 9;
static const uint32_t BOTA_DEVICE_SDK_V1_OPERATION_UPDATE_FIRMWARE = 10;
static const uint32_t BOTA_DEVICE_SDK_V1_OPERATION_READ_DEVICE_LOGS = 11;
static const uint32_t BOTA_DEVICE_SDK_V1_OPERATION_FACTORY_RESET = 12;
static const uint32_t BOTA_DEVICE_SDK_V1_OPERATION_UNKNOWN = 13;

static const uint32_t BOTA_DEVICE_SDK_V1_ERROR_INVALID_INPUT = 1;
static const uint32_t BOTA_DEVICE_SDK_V1_ERROR_TRUNCATED_PACKET = 2;
static const uint32_t BOTA_DEVICE_SDK_V1_ERROR_UNKNOWN_PACKET = 3;
static const uint32_t BOTA_DEVICE_SDK_V1_ERROR_PAYLOAD_TOO_LARGE = 4;
static const uint32_t BOTA_DEVICE_SDK_V1_ERROR_UNSUPPORTED_CAPABILITY = 5;
static const uint32_t BOTA_DEVICE_SDK_V1_ERROR_UNSUPPORTED_OPERATION = 6;
static const uint32_t BOTA_DEVICE_SDK_V1_ERROR_FEATURE_UNAVAILABLE = 7;
static const uint32_t BOTA_DEVICE_SDK_V1_ERROR_OPERATION_IN_PROGRESS = 8;
static const uint32_t BOTA_DEVICE_SDK_V1_ERROR_UNEXPECTED_EVENT = 9;
static const uint32_t BOTA_DEVICE_SDK_V1_ERROR_DEVICE_NOT_FOUND = 10;
static const uint32_t BOTA_DEVICE_SDK_V1_ERROR_IDENTITY_MISMATCH = 11;
static const uint32_t BOTA_DEVICE_SDK_V1_ERROR_CONNECTION_FAILED = 12;
static const uint32_t BOTA_DEVICE_SDK_V1_ERROR_PERSISTENCE_FAILED = 13;
static const uint32_t BOTA_DEVICE_SDK_V1_ERROR_NOT_CONNECTED = 14;
static const uint32_t BOTA_DEVICE_SDK_V1_ERROR_TIMEOUT = 15;
static const uint32_t BOTA_DEVICE_SDK_V1_ERROR_CANCELLED = 16;
static const uint32_t BOTA_DEVICE_SDK_V1_ERROR_PROTOCOL_REJECTED = 17;
static const uint32_t BOTA_DEVICE_SDK_V1_ERROR_INTEGRITY_FAILED = 18;
static const uint32_t BOTA_DEVICE_SDK_V1_ERROR_UPLOAD_OWNERSHIP_UNKNOWN = 19;
static const uint32_t BOTA_DEVICE_SDK_V1_ERROR_DOWNLOAD_FAILED = 20;
static const uint32_t BOTA_DEVICE_SDK_V1_ERROR_INTERNAL = 21;

typedef enum BotaDeviceSdkStatusV1 {
    BOTA_DEVICE_SDK_V1_OK = 0,
    BOTA_DEVICE_SDK_V1_NO_OUTPUT = 1,
    BOTA_DEVICE_SDK_V1_INVALID_ARGUMENT = -1,
    BOTA_DEVICE_SDK_V1_OPERATION_FAILED = -2,
    BOTA_DEVICE_SDK_V1_PANIC = -3,
    BOTA_DEVICE_SDK_V1_UNSUPPORTED_ABI = -4
} BotaDeviceSdkStatusV1;

typedef struct BotaDeviceSdkErrorViewV1 {
    uint32_t abi_version;
    uint32_t code;
    uint32_t operation;
    uint8_t retryable;
    uint8_t has_protocol_status;
    uint16_t protocol_status;
    BotaDeviceSdkSliceV1 detail;
} BotaDeviceSdkErrorViewV1;

uint32_t bota_device_sdk_v1_abi_version(void);
BotaDeviceSdkEngineV1 *bota_device_sdk_v1_engine_new(void);
void bota_device_sdk_v1_engine_free(BotaDeviceSdkEngineV1 *engine);
BotaDeviceSdkStatusV1 bota_device_sdk_v1_engine_cancel(
    BotaDeviceSdkEngineV1 *engine,
    uint64_t cancellation_id_high,
    uint64_t cancellation_id_low
);
BotaDeviceSdkStatusV1 bota_device_sdk_v1_engine_start(
    BotaDeviceSdkEngineV1 *engine,
    const BotaDeviceSdkPacketViewV1 *packet,
    uint64_t capability_bits
);
BotaDeviceSdkStatusV1 bota_device_sdk_v1_engine_poll_output(
    BotaDeviceSdkEngineV1 *engine,
    BotaDeviceSdkPacketV1 **out_packet
);
BotaDeviceSdkStatusV1 bota_device_sdk_v1_engine_dispatch(
    BotaDeviceSdkEngineV1 *engine,
    const BotaDeviceSdkPacketViewV1 *packet
);
BotaDeviceSdkStatusV1 bota_device_sdk_v1_protocol_decode(
    BotaDeviceSdkEngineV1 *engine,
    const BotaDeviceSdkPacketViewV1 *packet,
    BotaDeviceSdkPacketV1 **out_packet
);
BotaDeviceSdkStatusV1 bota_device_sdk_v1_protocol_encode(
    BotaDeviceSdkEngineV1 *engine,
    const BotaDeviceSdkPacketViewV1 *packet,
    BotaDeviceSdkPacketV1 **out_packet
);
BotaDeviceSdkStatusV1 bota_device_sdk_v1_engine_last_error(
    BotaDeviceSdkEngineV1 *engine,
    BotaDeviceSdkErrorV1 **out_error
);
BotaDeviceSdkStatusV1 bota_device_sdk_v1_error_view(
    const BotaDeviceSdkErrorV1 *error,
    BotaDeviceSdkErrorViewV1 *out_view
);
void bota_device_sdk_v1_error_free(BotaDeviceSdkErrorV1 *error);
BotaDeviceSdkStatusV1 bota_device_sdk_v1_packet_view(
    const BotaDeviceSdkPacketV1 *packet,
    BotaDeviceSdkPacketViewV1 *out_view
);
void bota_device_sdk_v1_packet_free(BotaDeviceSdkPacketV1 *packet);

#ifdef __cplusplus
}
#endif

#endif
