#ifndef BOTA_DEVICE_SDK_H
#define BOTA_DEVICE_SDK_H

/*
 * Bota Device SDK native ABI v1.
 *
 * Ownership and lifetime rules:
 * - An engine pointer must be NULL or a live value returned by engine_new.
 * - A live engine must not be freed while another call is using it.
 * - engine_free must be called at most once for each non-NULL engine.
 * - An error pointer is SDK-owned and must be passed exactly once to error_free.
 * - Slices returned by error_view are borrowed from the error owner and become
 *   invalid when that owner is freed.
 * - Output arguments must point to writable storage and must not retain an
 *   earlier SDK-owned value.
 *
 * Violating pointer, lifetime, or single-free rules is undefined behavior.
 * Status errors report recoverable operation failures, not invalid foreign
 * memory.
 */

#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

#define BOTA_DEVICE_SDK_ABI_VERSION UINT32_C(1)

typedef struct BotaDeviceSdkEngineV1 BotaDeviceSdkEngineV1;
typedef struct BotaDeviceSdkErrorV1 BotaDeviceSdkErrorV1;
typedef struct BotaDeviceSdkPacketV1 BotaDeviceSdkPacketV1;

typedef struct BotaDeviceSdkSliceV1 {
    const uint8_t *data;
    uint64_t len;
} BotaDeviceSdkSliceV1;

#define BOTA_DEVICE_SDK_V1_COMMAND_RANGE_START UINT32_C(0x0100)
#define BOTA_DEVICE_SDK_V1_COMMAND_DISCOVER_DEVICES UINT32_C(0x0101)
#define BOTA_DEVICE_SDK_V1_COMMAND_CONNECT UINT32_C(0x0102)
#define BOTA_DEVICE_SDK_V1_COMMAND_RECONNECT UINT32_C(0x0103)
#define BOTA_DEVICE_SDK_V1_COMMAND_PROVISION UINT32_C(0x0104)
#define BOTA_DEVICE_SDK_V1_COMMAND_TRANSFER_RECORDING UINT32_C(0x0105)
#define BOTA_DEVICE_SDK_V1_COMMAND_UPLOAD_RECORDING UINT32_C(0x0106)
#define BOTA_DEVICE_SDK_V1_COMMAND_UPDATE_FIRMWARE UINT32_C(0x0107)
#define BOTA_DEVICE_SDK_V1_COMMAND_READ_DEVICE_LOGS UINT32_C(0x0108)
#define BOTA_DEVICE_SDK_V1_COMMAND_FACTORY_RESET UINT32_C(0x0109)
#define BOTA_DEVICE_SDK_V1_COMMAND_RESUME_FACTORY_RESET UINT32_C(0x010A)
#define BOTA_DEVICE_SDK_V1_HOST_EVENT_RANGE_START UINT32_C(0x0200)
#define BOTA_DEVICE_SDK_V1_HOST_EVENT_BLE_SCAN_RESULT UINT32_C(0x0201)
#define BOTA_DEVICE_SDK_V1_HOST_EVENT_BLE_SCAN_STOPPED UINT32_C(0x0202)
#define BOTA_DEVICE_SDK_V1_HOST_EVENT_BLE_CONNECTED UINT32_C(0x0203)
#define BOTA_DEVICE_SDK_V1_HOST_EVENT_BLE_SERVICES_DISCOVERED UINT32_C(0x0204)
#define BOTA_DEVICE_SDK_V1_HOST_EVENT_BLE_SUBSCRIBED UINT32_C(0x0205)
#define BOTA_DEVICE_SDK_V1_HOST_EVENT_BLE_DISCONNECTED UINT32_C(0x0206)
#define BOTA_DEVICE_SDK_V1_HOST_EVENT_BLE_READ_COMPLETED UINT32_C(0x0207)
#define BOTA_DEVICE_SDK_V1_HOST_EVENT_BLE_WRITE_COMPLETED UINT32_C(0x0208)
#define BOTA_DEVICE_SDK_V1_HOST_EVENT_BLE_NOTIFICATION UINT32_C(0x0209)
#define BOTA_DEVICE_SDK_V1_HOST_EVENT_BLE_FAILED UINT32_C(0x020A)
#define BOTA_DEVICE_SDK_V1_HOST_EVENT_TIMER_FIRED UINT32_C(0x0210)
#define BOTA_DEVICE_SDK_V1_HOST_EVENT_CHECKPOINT_LOADED UINT32_C(0x0211)
#define BOTA_DEVICE_SDK_V1_HOST_EVENT_CHECKPOINT_SAVED UINT32_C(0x0212)
#define BOTA_DEVICE_SDK_V1_HOST_EVENT_CONNECTION_IDENTITY_SAVED UINT32_C(0x0213)
#define BOTA_DEVICE_SDK_V1_HOST_EVENT_FACTORY_RESET_RESULT_SAVED UINT32_C(0x0214)
#define BOTA_DEVICE_SDK_V1_HOST_EVENT_FACTORY_RESET_RESULT_DELETED UINT32_C(0x0215)
#define BOTA_DEVICE_SDK_V1_HOST_EVENT_PERSISTENCE_FAILED UINT32_C(0x0216)
#define BOTA_DEVICE_SDK_V1_HOST_EVENT_PROVISIONING_MATERIAL_PREPARED UINT32_C(0x0217)
#define BOTA_DEVICE_SDK_V1_HOST_EVENT_FACTORY_RESET_GRANT_PREPARED UINT32_C(0x0218)
#define BOTA_DEVICE_SDK_V1_HOST_EVENT_HOST_MATERIAL_FAILED UINT32_C(0x0219)
#define BOTA_DEVICE_SDK_V1_HOST_EVENT_RECORDING_SINK_TRUNCATED UINT32_C(0x021A)
#define BOTA_DEVICE_SDK_V1_HOST_EVENT_RECORDING_SINK_APPEND_COMPLETED UINT32_C(0x021B)
#define BOTA_DEVICE_SDK_V1_HOST_EVENT_RECORDING_SINK_FINALIZED UINT32_C(0x021C)
#define BOTA_DEVICE_SDK_V1_HOST_EVENT_RECORDING_SINK_INTEGRITY_FAILED UINT32_C(0x021D)
#define BOTA_DEVICE_SDK_V1_HOST_EVENT_RECORDING_SINK_FAILED UINT32_C(0x021E)
#define BOTA_DEVICE_SDK_V1_HOST_EVENT_FIRMWARE_CHUNK_READ UINT32_C(0x021F)
#define BOTA_DEVICE_SDK_V1_HOST_EVENT_FIRMWARE_BLOB_FAILED UINT32_C(0x0220)
#define BOTA_DEVICE_SDK_V1_HOST_EVENT_SECRET_LOADED UINT32_C(0x0221)
#define BOTA_DEVICE_SDK_V1_HOST_EVENT_SECRET_STORED UINT32_C(0x0222)
#define BOTA_DEVICE_SDK_V1_HOST_EVENT_NETWORK_DOWNLOAD_PROGRESS UINT32_C(0x0223)
#define BOTA_DEVICE_SDK_V1_HOST_EVENT_NETWORK_DOWNLOAD_COMPLETED UINT32_C(0x0224)
#define BOTA_DEVICE_SDK_V1_HOST_EVENT_NETWORK_UPLOAD_PROGRESS UINT32_C(0x0225)
#define BOTA_DEVICE_SDK_V1_HOST_EVENT_NETWORK_UPLOAD_COMPLETED UINT32_C(0x0226)
#define BOTA_DEVICE_SDK_V1_HOST_EVENT_NETWORK_FAILED UINT32_C(0x0227)
#define BOTA_DEVICE_SDK_V1_HOST_EFFECT_RANGE_START UINT32_C(0x0300)
#define BOTA_DEVICE_SDK_V1_HOST_EFFECT_TIMER_SCHEDULE UINT32_C(0x0301)
#define BOTA_DEVICE_SDK_V1_HOST_EFFECT_TIMER_CANCEL UINT32_C(0x0302)
#define BOTA_DEVICE_SDK_V1_HOST_EFFECT_PERSISTENCE_LOAD_CHECKPOINT UINT32_C(0x0303)
#define BOTA_DEVICE_SDK_V1_HOST_EFFECT_PERSISTENCE_SAVE_CHECKPOINT UINT32_C(0x0304)
#define BOTA_DEVICE_SDK_V1_HOST_EFFECT_PERSISTENCE_DELETE_CHECKPOINT UINT32_C(0x0305)
#define BOTA_DEVICE_SDK_V1_HOST_EFFECT_PERSISTENCE_SAVE_CONNECTION_IDENTITY UINT32_C(0x0306)
#define BOTA_DEVICE_SDK_V1_HOST_EFFECT_PERSISTENCE_SAVE_FACTORY_RESET_RESULT UINT32_C(0x0307)
#define BOTA_DEVICE_SDK_V1_HOST_EFFECT_PERSISTENCE_DELETE_FACTORY_RESET_RESULT UINT32_C(0x0308)
#define BOTA_DEVICE_SDK_V1_HOST_EFFECT_SECURE_STORAGE_READ UINT32_C(0x0309)
#define BOTA_DEVICE_SDK_V1_HOST_EFFECT_SECURE_STORAGE_WRITE UINT32_C(0x030A)
#define BOTA_DEVICE_SDK_V1_HOST_EFFECT_SECURE_STORAGE_DELETE UINT32_C(0x030B)
#define BOTA_DEVICE_SDK_V1_HOST_EFFECT_BLE_START_SCAN UINT32_C(0x0310)
#define BOTA_DEVICE_SDK_V1_HOST_EFFECT_BLE_STOP_SCAN UINT32_C(0x0311)
#define BOTA_DEVICE_SDK_V1_HOST_EFFECT_BLE_CONNECT UINT32_C(0x0312)
#define BOTA_DEVICE_SDK_V1_HOST_EFFECT_BLE_DISCOVER_SERVICES UINT32_C(0x0313)
#define BOTA_DEVICE_SDK_V1_HOST_EFFECT_BLE_DISCONNECT UINT32_C(0x0314)
#define BOTA_DEVICE_SDK_V1_HOST_EFFECT_BLE_READ UINT32_C(0x0315)
#define BOTA_DEVICE_SDK_V1_HOST_EFFECT_BLE_WRITE UINT32_C(0x0316)
#define BOTA_DEVICE_SDK_V1_HOST_EFFECT_BLE_SUBSCRIBE UINT32_C(0x0317)
#define BOTA_DEVICE_SDK_V1_HOST_EFFECT_BLE_UNSUBSCRIBE UINT32_C(0x0318)
#define BOTA_DEVICE_SDK_V1_HOST_EFFECT_NETWORK_DOWNLOAD UINT32_C(0x0320)
#define BOTA_DEVICE_SDK_V1_HOST_EFFECT_NETWORK_UPLOAD UINT32_C(0x0321)
#define BOTA_DEVICE_SDK_V1_HOST_EFFECT_PROGRESS UINT32_C(0x0328)
#define BOTA_DEVICE_SDK_V1_HOST_EFFECT_PREPARE_PROVISIONING UINT32_C(0x0330)
#define BOTA_DEVICE_SDK_V1_HOST_EFFECT_PREPARE_FACTORY_RESET_GRANT UINT32_C(0x0331)
#define BOTA_DEVICE_SDK_V1_HOST_EFFECT_RECORDING_SINK_TRUNCATE UINT32_C(0x0338)
#define BOTA_DEVICE_SDK_V1_HOST_EFFECT_RECORDING_SINK_APPEND UINT32_C(0x0339)
#define BOTA_DEVICE_SDK_V1_HOST_EFFECT_RECORDING_SINK_FINALIZE UINT32_C(0x033A)
#define BOTA_DEVICE_SDK_V1_HOST_EFFECT_RECORDING_SINK_DISCARD UINT32_C(0x033B)
#define BOTA_DEVICE_SDK_V1_HOST_EFFECT_FIRMWARE_BLOB_READ UINT32_C(0x0340)
#define BOTA_DEVICE_SDK_V1_NOTIFICATION_RANGE_START UINT32_C(0x0400)
#define BOTA_DEVICE_SDK_V1_NOTIFICATION_STARTED UINT32_C(0x0401)
#define BOTA_DEVICE_SDK_V1_NOTIFICATION_DEVICE_DISCOVERED UINT32_C(0x0402)
#define BOTA_DEVICE_SDK_V1_NOTIFICATION_CONNECTION_ESTABLISHED UINT32_C(0x0403)
#define BOTA_DEVICE_SDK_V1_NOTIFICATION_PROGRESS UINT32_C(0x0404)
#define BOTA_DEVICE_SDK_V1_NOTIFICATION_RETRYING UINT32_C(0x0405)
#define BOTA_DEVICE_SDK_V1_NOTIFICATION_DEVICE_UPLOAD_PRESERVED UINT32_C(0x0406)
#define BOTA_DEVICE_SDK_V1_NOTIFICATION_BLE_FALLBACK_READY UINT32_C(0x0407)
#define BOTA_DEVICE_SDK_V1_NOTIFICATION_FIRMWARE_PROGRESS UINT32_C(0x0408)
#define BOTA_DEVICE_SDK_V1_NOTIFICATION_DEVICE_LOG UINT32_C(0x0409)
#define BOTA_DEVICE_SDK_V1_NOTIFICATION_COMPLETED UINT32_C(0x040A)
#define BOTA_DEVICE_SDK_V1_NOTIFICATION_CANCELLED UINT32_C(0x040B)
#define BOTA_DEVICE_SDK_V1_NOTIFICATION_FAILED UINT32_C(0x040C)
#define BOTA_DEVICE_SDK_V1_PROTOCOL_VALUE_RANGE_START UINT32_C(0x0500)

#define BOTA_DEVICE_SDK_V1_FIELD_TYPE_UNSIGNED UINT32_C(1)
#define BOTA_DEVICE_SDK_V1_FIELD_TYPE_SIGNED UINT32_C(2)
#define BOTA_DEVICE_SDK_V1_FIELD_TYPE_BOOL UINT32_C(3)
#define BOTA_DEVICE_SDK_V1_FIELD_TYPE_UTF8 UINT32_C(4)
#define BOTA_DEVICE_SDK_V1_FIELD_TYPE_BYTES UINT32_C(5)

#define BOTA_DEVICE_SDK_V1_FIELD_TIMEOUT_MS UINT32_C(1)
#define BOTA_DEVICE_SDK_V1_FIELD_ALLOW_DUPLICATES UINT32_C(2)
#define BOTA_DEVICE_SDK_V1_FIELD_SERIAL_NUMBER UINT32_C(3)
#define BOTA_DEVICE_SDK_V1_FIELD_PERIPHERAL_ID UINT32_C(4)
#define BOTA_DEVICE_SDK_V1_FIELD_NAME UINT32_C(5)
#define BOTA_DEVICE_SDK_V1_FIELD_ADVERTISED_ADDRESS UINT32_C(6)
#define BOTA_DEVICE_SDK_V1_FIELD_RSSI UINT32_C(7)
#define BOTA_DEVICE_SDK_V1_FIELD_STORED_PERIPHERAL_ID UINT32_C(8)
#define BOTA_DEVICE_SDK_V1_FIELD_STORED_NAME UINT32_C(9)
#define BOTA_DEVICE_SDK_V1_FIELD_SCAN_TIMEOUT_MS UINT32_C(10)
#define BOTA_DEVICE_SDK_V1_FIELD_CONNECTION_TIMEOUT_MS UINT32_C(11)
#define BOTA_DEVICE_SDK_V1_FIELD_MATERIAL_ID UINT32_C(12)
#define BOTA_DEVICE_SDK_V1_FIELD_RECORDING_UUID UINT32_C(13)
#define BOTA_DEVICE_SDK_V1_FIELD_SINK_ID UINT32_C(14)
#define BOTA_DEVICE_SDK_V1_FIELD_TOTAL_UNITS UINT32_C(15)
#define BOTA_DEVICE_SDK_V1_FIELD_UPLOAD_ID UINT32_C(16)
#define BOTA_DEVICE_SDK_V1_FIELD_DESTINATION_ID UINT32_C(17)
#define BOTA_DEVICE_SDK_V1_FIELD_FIRMWARE_VERSION UINT32_C(18)
#define BOTA_DEVICE_SDK_V1_FIELD_FIRMWARE_SIZE_BYTES UINT32_C(19)
#define BOTA_DEVICE_SDK_V1_FIELD_FIRMWARE_CRC32 UINT32_C(20)
#define BOTA_DEVICE_SDK_V1_FIELD_DOWNLOAD_ID UINT32_C(21)
#define BOTA_DEVICE_SDK_V1_FIELD_COMMAND_ID UINT32_C(22)
#define BOTA_DEVICE_SDK_V1_FIELD_GRANT_ID UINT32_C(23)
#define BOTA_DEVICE_SDK_V1_FIELD_RESULT_CODE UINT32_C(24)
#define BOTA_DEVICE_SDK_V1_FIELD_DELETED_RECORDING_COUNT UINT32_C(25)
#define BOTA_DEVICE_SDK_V1_FIELD_TIMER_ID UINT32_C(26)
#define BOTA_DEVICE_SDK_V1_FIELD_DELAY_MS UINT32_C(27)
#define BOTA_DEVICE_SDK_V1_FIELD_CHECKPOINT UINT32_C(28)
#define BOTA_DEVICE_SDK_V1_FIELD_KEY UINT32_C(29)
#define BOTA_DEVICE_SDK_V1_FIELD_VALUE UINT32_C(30)
#define BOTA_DEVICE_SDK_V1_FIELD_SERVICE_UUID UINT32_C(31)
#define BOTA_DEVICE_SDK_V1_FIELD_CHARACTERISTIC_UUID UINT32_C(32)
#define BOTA_DEVICE_SDK_V1_FIELD_PAYLOAD UINT32_C(33)
#define BOTA_DEVICE_SDK_V1_FIELD_WITH_RESPONSE UINT32_C(34)
#define BOTA_DEVICE_SDK_V1_FIELD_UPLOAD_SOURCE UINT32_C(35)
#define BOTA_DEVICE_SDK_V1_FIELD_COMPLETED_UNITS UINT32_C(36)
#define BOTA_DEVICE_SDK_V1_FIELD_EXPECTED_CRC32 UINT32_C(37)
#define BOTA_DEVICE_SDK_V1_FIELD_SEQUENCE UINT32_C(38)
#define BOTA_DEVICE_SDK_V1_FIELD_OFFSET UINT32_C(39)
#define BOTA_DEVICE_SDK_V1_FIELD_MAX_LENGTH UINT32_C(40)
#define BOTA_DEVICE_SDK_V1_FIELD_NONCE UINT32_C(41)
#define BOTA_DEVICE_SDK_V1_FIELD_DEVICE_PUBLIC_KEY UINT32_C(42)
#define BOTA_DEVICE_SDK_V1_FIELD_ATTEMPT UINT32_C(43)
#define BOTA_DEVICE_SDK_V1_FIELD_CONNECTION_MODE UINT32_C(44)
#define BOTA_DEVICE_SDK_V1_FIELD_FIRMWARE_PHASE UINT32_C(45)
#define BOTA_DEVICE_SDK_V1_FIELD_LOG_MESSAGE UINT32_C(46)
#define BOTA_DEVICE_SDK_V1_FIELD_ERROR_CODE UINT32_C(47)
#define BOTA_DEVICE_SDK_V1_FIELD_RETRYABLE UINT32_C(48)
#define BOTA_DEVICE_SDK_V1_FIELD_PROTOCOL_STATUS UINT32_C(49)
#define BOTA_DEVICE_SDK_V1_FIELD_ERROR_DETAIL UINT32_C(50)
#define BOTA_DEVICE_SDK_V1_FIELD_IS_BACKLOG UINT32_C(51)
#define BOTA_DEVICE_SDK_V1_FIELD_PLATFORM_CODE UINT32_C(52)
#define BOTA_DEVICE_SDK_V1_FIELD_REASON_CODE UINT32_C(53)
#define BOTA_DEVICE_SDK_V1_FIELD_DURABLE_UNITS UINT32_C(54)
#define BOTA_DEVICE_SDK_V1_FIELD_API_ENDPOINT UINT32_C(55)
#define BOTA_DEVICE_SDK_V1_FIELD_DEVICE_TOKEN UINT32_C(56)
#define BOTA_DEVICE_SDK_V1_FIELD_MTU UINT32_C(57)
#define BOTA_DEVICE_SDK_V1_FIELD_GRANT UINT32_C(58)
#define BOTA_DEVICE_SDK_V1_FIELD_TRANSFER_ID UINT32_C(59)
#define BOTA_DEVICE_SDK_V1_FIELD_STATUS_CODE UINT32_C(60)

#define BOTA_DEVICE_SDK_V1_CAPABILITY_BLE (UINT64_C(1) << 0)
#define BOTA_DEVICE_SDK_V1_CAPABILITY_TIMER (UINT64_C(1) << 1)
#define BOTA_DEVICE_SDK_V1_CAPABILITY_PERSISTENCE (UINT64_C(1) << 2)
#define BOTA_DEVICE_SDK_V1_CAPABILITY_SECURE_STORAGE (UINT64_C(1) << 3)
#define BOTA_DEVICE_SDK_V1_CAPABILITY_NETWORK_TRANSFER (UINT64_C(1) << 4)
#define BOTA_DEVICE_SDK_V1_CAPABILITY_PROGRESS (UINT64_C(1) << 5)
#define BOTA_DEVICE_SDK_V1_CAPABILITY_HOST_MATERIAL (UINT64_C(1) << 6)
#define BOTA_DEVICE_SDK_V1_CAPABILITY_RECORDING_SINK (UINT64_C(1) << 7)
#define BOTA_DEVICE_SDK_V1_CAPABILITY_FIRMWARE_BLOB (UINT64_C(1) << 8)

typedef struct BotaDeviceSdkFieldViewV1 {
    uint32_t field_id;
    uint32_t field_type;
    uint64_t unsigned_value;
    int64_t signed_value;
    BotaDeviceSdkSliceV1 data;
} BotaDeviceSdkFieldViewV1;

typedef struct BotaDeviceSdkPacketViewV1 {
    uint32_t abi_version;
    uint32_t kind;
    uint32_t operation;
    uint32_t reserved;
    uint64_t request_id;
    uint64_t cancellation_id_high;
    uint64_t cancellation_id_low;
    const BotaDeviceSdkFieldViewV1 *fields;
    uint64_t field_count;
} BotaDeviceSdkPacketViewV1;

#define BOTA_DEVICE_SDK_V1_OPERATION_VALIDATE UINT32_C(1)
#define BOTA_DEVICE_SDK_V1_OPERATION_DECODE UINT32_C(2)
#define BOTA_DEVICE_SDK_V1_OPERATION_ENCODE UINT32_C(3)
#define BOTA_DEVICE_SDK_V1_OPERATION_DISCOVER UINT32_C(4)
#define BOTA_DEVICE_SDK_V1_OPERATION_CONNECT UINT32_C(5)
#define BOTA_DEVICE_SDK_V1_OPERATION_RECONNECT UINT32_C(6)
#define BOTA_DEVICE_SDK_V1_OPERATION_PROVISION UINT32_C(7)
#define BOTA_DEVICE_SDK_V1_OPERATION_TRANSFER_RECORDING UINT32_C(8)
#define BOTA_DEVICE_SDK_V1_OPERATION_UPLOAD UINT32_C(9)
#define BOTA_DEVICE_SDK_V1_OPERATION_UPDATE_FIRMWARE UINT32_C(10)
#define BOTA_DEVICE_SDK_V1_OPERATION_READ_DEVICE_LOGS UINT32_C(11)
#define BOTA_DEVICE_SDK_V1_OPERATION_FACTORY_RESET UINT32_C(12)
#define BOTA_DEVICE_SDK_V1_OPERATION_UNKNOWN UINT32_C(13)

#define BOTA_DEVICE_SDK_V1_ERROR_INVALID_INPUT UINT32_C(1)
#define BOTA_DEVICE_SDK_V1_ERROR_TRUNCATED_PACKET UINT32_C(2)
#define BOTA_DEVICE_SDK_V1_ERROR_UNKNOWN_PACKET UINT32_C(3)
#define BOTA_DEVICE_SDK_V1_ERROR_PAYLOAD_TOO_LARGE UINT32_C(4)
#define BOTA_DEVICE_SDK_V1_ERROR_UNSUPPORTED_CAPABILITY UINT32_C(5)
#define BOTA_DEVICE_SDK_V1_ERROR_UNSUPPORTED_OPERATION UINT32_C(6)
#define BOTA_DEVICE_SDK_V1_ERROR_FEATURE_UNAVAILABLE UINT32_C(7)
#define BOTA_DEVICE_SDK_V1_ERROR_OPERATION_IN_PROGRESS UINT32_C(8)
#define BOTA_DEVICE_SDK_V1_ERROR_UNEXPECTED_EVENT UINT32_C(9)
#define BOTA_DEVICE_SDK_V1_ERROR_DEVICE_NOT_FOUND UINT32_C(10)
#define BOTA_DEVICE_SDK_V1_ERROR_IDENTITY_MISMATCH UINT32_C(11)
#define BOTA_DEVICE_SDK_V1_ERROR_CONNECTION_FAILED UINT32_C(12)
#define BOTA_DEVICE_SDK_V1_ERROR_PERSISTENCE_FAILED UINT32_C(13)
#define BOTA_DEVICE_SDK_V1_ERROR_NOT_CONNECTED UINT32_C(14)
#define BOTA_DEVICE_SDK_V1_ERROR_TIMEOUT UINT32_C(15)
#define BOTA_DEVICE_SDK_V1_ERROR_CANCELLED UINT32_C(16)
#define BOTA_DEVICE_SDK_V1_ERROR_PROTOCOL_REJECTED UINT32_C(17)
#define BOTA_DEVICE_SDK_V1_ERROR_INTEGRITY_FAILED UINT32_C(18)
#define BOTA_DEVICE_SDK_V1_ERROR_UPLOAD_OWNERSHIP_UNKNOWN UINT32_C(19)
#define BOTA_DEVICE_SDK_V1_ERROR_DOWNLOAD_FAILED UINT32_C(20)
#define BOTA_DEVICE_SDK_V1_ERROR_INTERNAL UINT32_C(21)

typedef enum BotaDeviceSdkStatusV1 {
    BOTA_DEVICE_SDK_V1_OK = 0,
    BOTA_DEVICE_SDK_V1_NO_OUTPUT = 1,
    BOTA_DEVICE_SDK_V1_INVALID_ARGUMENT = -1,
    BOTA_DEVICE_SDK_V1_OPERATION_FAILED = -2,
    BOTA_DEVICE_SDK_V1_PANIC = -3,
    BOTA_DEVICE_SDK_V1_UNSUPPORTED_ABI = -4
} BotaDeviceSdkStatusV1;

typedef struct BotaDeviceSdkErrorViewV1 {
    uint32_t abi_version;
    uint32_t code;
    uint32_t operation;
    uint8_t retryable;
    uint8_t has_protocol_status;
    uint16_t protocol_status;
    BotaDeviceSdkSliceV1 detail;
} BotaDeviceSdkErrorViewV1;

uint32_t bota_device_sdk_v1_abi_version(void);
BotaDeviceSdkEngineV1 *bota_device_sdk_v1_engine_new(void);
void bota_device_sdk_v1_engine_free(BotaDeviceSdkEngineV1 *engine);
BotaDeviceSdkStatusV1 bota_device_sdk_v1_engine_cancel(
    BotaDeviceSdkEngineV1 *engine,
    uint64_t cancellation_id_high,
    uint64_t cancellation_id_low
);
BotaDeviceSdkStatusV1 bota_device_sdk_v1_engine_start(
    BotaDeviceSdkEngineV1 *engine,
    const BotaDeviceSdkPacketViewV1 *packet,
    uint64_t capability_bits
);
BotaDeviceSdkStatusV1 bota_device_sdk_v1_engine_poll_output(
    BotaDeviceSdkEngineV1 *engine,
    BotaDeviceSdkPacketV1 **out_packet
);
BotaDeviceSdkStatusV1 bota_device_sdk_v1_engine_dispatch(
    BotaDeviceSdkEngineV1 *engine,
    const BotaDeviceSdkPacketViewV1 *packet
);
BotaDeviceSdkStatusV1 bota_device_sdk_v1_engine_last_error(
    BotaDeviceSdkEngineV1 *engine,
    BotaDeviceSdkErrorV1 **out_error
);
BotaDeviceSdkStatusV1 bota_device_sdk_v1_error_view(
    const BotaDeviceSdkErrorV1 *error,
    BotaDeviceSdkErrorViewV1 *out_view
);
void bota_device_sdk_v1_error_free(BotaDeviceSdkErrorV1 *error);
BotaDeviceSdkStatusV1 bota_device_sdk_v1_packet_view(
    const BotaDeviceSdkPacketV1 *packet,
    BotaDeviceSdkPacketViewV1 *out_view
);
void bota_device_sdk_v1_packet_free(BotaDeviceSdkPacketV1 *packet);

#ifdef __cplusplus
}
#endif

#endif
